codecov:
  token: $CODECOV_TOKEN
  ci:
    - "circleci"
  max_report_age: 24
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: no
  status:
    project:
      default: true
      tests:
        target: auto
        threshold: 100%
        paths: "*/"
