codecov:
  token: $CODECOV_TOKEN
  branch: master
  ci:
    - "circleci"
  strict_yaml_branch: "master"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: no
