# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world of code coverage"
      - run: pip install coverage pytest pytest-cov
      - run: coverage run test_num_paths.py
      - run: coverage report
      - run: coverage html
      - run: coverage xml
      - run: bash <(curl -s https://codecov.io/bash)
